### ISSUE TITLE
[BUG] Non-crashing conflict w/ AkashicTome listed by VanillaFix

### ISSUE THREAD

**Issue by Royal-Jelly** [T145/metaltransport#13]
It doesn't crash however the server-side gets spam with a few things now with Vanilla-fix installed [**Full Hastebin Log**](https://paste.dimdev.org/tehajukogo.md) , and a Massive ish Snip :

```
[12:27:17] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.func_78013_b()Ljava/lang/String;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_212]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.func_78013_b()Ljava/lang/String;
	at T145.tbone.api.ITItem.getCreatorModId(ITItem.java:57) ~[ITItem.class:?]
	at T145.tbone.items.TItem.getCreatorModId(TItem.java:60) ~[TItem.class:?]
	at vazkii.akashictome.MorphingHandler.getModFromStack(MorphingHandler.java:86) ~[MorphingHandler.class:?]
	at vazkii.akashictome.AttachementRecipe.isTarget(AttachementRecipe.java:87) ~[AttachementRecipe.class:?]
	at vazkii.akashictome.AttachementRecipe.matches(AttachementRecipe.java:26) ~[AttachementRecipe.class:?]
	at net.minecraft.item.crafting.CraftingManager.findMatchingRecipe(CraftingManager.java:213) ~[aku.class:?]
	at net.minecraft.inventory.Container.slotChangedCraftingGrid(Container.java:793) ~[afr.class:?]
	at net.minecraft.inventory.ContainerPlayer.onCraftMatrixChanged(ContainerPlayer.java:88) ~[agi.class:?]
	at net.minecraft.inventory.InventoryCrafting.setInventorySlotContents(SourceFile:93) ~[afy.class:?]
	at net.minecraft.inventory.Slot.putStack(Slot.java:70) ~[agr.class:?]
	at net.minecraft.inventory.Container.slotClick(Container.java:281) ~[afr.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processClickWindow(NetHandlerPlayServer.java:1162) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.processPacket(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.processPacket(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
```

Environment:
-   OS: Linux Mint 19
-   Full Forge version: 14.23.5.2838 [1.12.2]
-   Mod version: Metal Transport 2.5.2

**Comment by T145** [comment]
This seems to be occurring b/c AkashicTome is trying to call `getTabLabel` from the creative tab one of my items:
```
Caused by: java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.func_78013_b()Ljava/lang/String;
	at T145.tbone.api.ITItem.getCreatorModId(ITItem.java:57) ~[ITItem.class:?]
	at T145.tbone.items.TItem.getCreatorModId(TItem.java:60) ~[TItem.class:?]
	at vazkii.akashictome.MorphingHandler.getModFromStack(MorphingHandler.java:86) ~[MorphingHandler.class:?]
	at vazkii.akashictome.AttachementRecipe.isTarget(AttachementRecipe.java:87) ~[AttachementRecipe.class:?]
	at vazkii.akashictome.AttachementRecipe.matches(AttachementRecipe.java:26) ~[AttachementRecipe.class:?]
```
Why it's doing so I'm not sure. Try creating a small pack w/ just Metal Transport, TBone, Fast Workbench, Metal Chests & VanillaFix installed, then test and see if there's any output. Then throw in AkashicTome & AutoRegLib to see if the issue persists.

**Comment by Royal-Jelly** [comment]
i feel kinda slow yeah not having akashictome installed does fix the serveside spam

**Comment by T145** [comment]
Resolved this problem here: https://github.com/T145/tbone/commit/37d899a81bc30123133e1ff364e78721c8fdfa4c
