### ISSUE TITLE
[Crash] Placing a Spawner Minecart

### ISSUE THREAD

**Issue by WenXin20** [T145/metaltransport#8]
## Problem Details
Minecraft v1.12.2
Forge v14.23.5.2838
Metal Transport v2.1.1

I got this crash after placing a Copper Minecart w/ a Spawner onto a rail. The item was taken from JEI's menu.

[Crash Report](https://paste.dimdev.org/owaxowukip.mccrash)

**Comment by T145** [comment]
Hm, the access transformer is shipped w/ the mod. Not sure why the spawner logic field is inaccessible; I'll look into it.

**Comment by WenXin20** [comment]
This was also printed in the log:
```
[19:19:05] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.RenderManager.renderEntity(RenderManager.java:454) ~[bzf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.renderEntityStatic(RenderManager.java:392) ~[bzf.class:?]
	at net.minecraft.client.renderer.RenderGlobal.redirect$renderEntityStatic$zcl000(RenderGlobal.java:4227) ~[buy.class:?]
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:839) ~[buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1800) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1613) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1384) ~[buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) ~[bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.entity.item.EntityMinecartMobSpawner.field_98040_a from class t145.metaltransport.client.render.entities.RenderSpawnerCart
	at t145.metaltransport.client.render.entities.RenderSpawnerCart.renderCartContents(RenderSpawnerCart.java:24) ~[RenderSpawnerCart.class:?]
	at net.minecraft.client.renderer.entity.RenderMinecart.doRender(SourceFile:99) ~[cad.class:?]
	at net.minecraft.client.renderer.entity.RenderMinecart.doRender(SourceFile:15) ~[cad.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.renderEntity(RenderManager.java:412) ~[bzf.class:?]
	... 15 more
```

**Comment by WenXin20** [comment]
Thanks for all the help!
